# Generated by Django 3.2.9 on 2021-11-09 13:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuardStrategy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.UUIDField(db_index=True, null=True)),
                ('name', models.CharField(max_length=72)),
                ('config', models.JSONField()),
            ],
        ),
    ]
